spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1434;databaseName=Student2;Encrypt=false;trustServerCertificate=false
    username: sa
    password: 123

  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      #      ddl-auto: create
      ddl-auto: update
    show-sql: true